### PR TITLE
Parses more functions inside {$IF} directive handler

### PR DESCRIPTION
**Pull request by LeoUpperThrower4**
Added handler for 3 more if cases:

- RTLVersion
> {$IF RTLVersion > 5}
- SizeOf
> {$IF SizeOf(Pointer) = 4}
- CompilerVersion
> {$IF CompilerVersion >33}

### CODE REVIEW

**Comment by michaliskambi** [comment]
Thank you!

1. Jenkins reports compilation errors with FPC 3.2.2:

    ```
    PasDoc_Scanner.pas(1097,17) Error: Identifier not found "RTLVersion"
    PasDoc_Scanner.pas(1104,17) Error: Identifier not found "RTLVersion"
    PasDoc_Scanner.pas(1111,17) Error: Identifier not found "RTLVersion"
    PasDoc_Scanner.pas(1118,17) Error: Identifier not found "RTLVersion"
    PasDoc_Scanner.pas(1125,17) Error: Identifier not found "RTLVersion"
    PasDoc_Scanner.pas(1211,17) Error: Identifier not found "CompilerVersion"
    PasDoc_Scanner.pas(1218,17) Error: Identifier not found "CompilerVersion"
    PasDoc_Scanner.pas(1225,17) Error: Identifier not found "CompilerVersion"
    PasDoc_Scanner.pas(1232,17) Error: Identifier not found "CompilerVersion"
    PasDoc_Scanner.pas(1239,17) Error: Identifier not found "CompilerVersion"
    ```

2. In general, we don't want to assume that compilation environment when building PasDoc is the one you use for compiling your final project. That is also why e.g. PasDoc doesn't define some compiler/platform symbols (like `FPC` or `MSWINDOWS`) even when they are defined when compiling PasDoc itself, see https://pasdoc.github.io/ConditionalDefines . Your project may use different compiler/platform than the one where we build PasDoc.

    This means that, even when PasDoc is compiled with Delphi, it should not really look at current `RTLVersion` and `CompilerVersion` to calculate these expressions. And `SizeOf` should be independent from current PasDoc environment too. E.g. generated documentation should be the same, regardless if you used PasDoc compiled for Win32 or Win64. Because the architecture of PasDoc EXE isn't really related to the architecture you use for your Pascal project.

    I propose: for now, just make these things simple global variables in PasDoc_Scanner:

    ```
    var
      TargetCompilerVersion = ...;
      TargetRTLVersion = ...;
      TargetSizeOfPointer = 8; // by default, assume 64-bit platform
    ```

    Adjust them to follow latest Delphi 11 values.

    And when evaluating them, add a message: 

    ```
   DoMessage(2, pmtWarning, 'Evaluating $f condition assuming that your project is compiled with CompilerVersion: %d', [TargetCompilerVersion]);
    ```

    This way it is clear for users what is going on. They can accept the way it works now, or use a special symbol (like `PASDOC`) to completely avoid testing things like `CompilerVersion` etc. when the code is parsed by PasDoc.
    
3. Add a testcase for it. Just create a unit like `ok_extra_if_checks.pas` (the name is just my proposal, it can be any `ok_*.pas`) and place it inside `tests/testcases/`, and add there some example usage of `{$IF RTLVersion > 5}` etc. 

    This way we can 1. easily test that the feature works, 2. Jenkins will check that it always works after every commit, because we can add "valid output" for such tests. You can also see for yourself whether the tests work, and generate valid output, following docs on https://github.com/pasdoc/pasdoc/tree/master/tests . Note that it requires FPC, and is admittedly more comfortable on Unix than Windows. So you can as well leave this up to me :)

**Comment by Fr0sT-Brutal** [comment]
Agree. Doc generator must handle any set of compiler defines/constants. I doubt anyone would be happy to build pasdoc binary for EVERY set of possible combinations just to gen proper output. However, recognition of these clauses are good - but actual values just have to be set via input parameters just like defines currently.

**Comment by michaliskambi** [comment]
> but actual values just have to be set via input parameters just like defines currently.

Exactly. I'd propose to just make these things global variables within this PR, without any command-line parameters to change them...

And later figure out a way to set them (by command-line and PasDoc GUI). 

For command-line, I'd propose to extend current `--define` and `--conditionals` options on https://pasdoc.github.io/ConditionalDefines . Right now they require defines to be separated by comma (for `--define`) or newlines (in file pointed to in `--conditionals`). So it should be possible to allow there syntax to add `XXX=YYY`, and allow 

```
pasdoc --define CompilerVersion=123
pasdoc --define RTLVersion=456
pasdoc --define DEBUG,RTLVersion=456,CompilerVersion=123
```

Likewise, `--conditionals` should allow a file like this:

```
DEBUG
RTLVersion=456
CompilerVersion=123
```

I do not yet have a good idea how to allow user to define Pointer size. Maybe we should just treat defines like `CPU64`, `CPU32` special: if you do e.g.

```
pasdoc --define CPU32
```

then we 
1. add CPU32 symbol
2. set `TargetSizeOfPointer ` that I propose above to 4

**Comment by Fr0sT-Brutal** [comment]
> I do not yet have a good idea how to allow user to define Pointer size.

Don't forget that SizeOf could have any type inside. I think necessary values should be simply defined just like any other constant: `--define SizeOf(TSomeType)=345`. Then handling of this IF could even be downgraded to common `IF Const` clause (I mean, we could just pretend we have a const named `SizeOf(TSomeType)`)

**Pull request closed without merging**
