### PR TITLE
Implement Markdown URL `[Descr](someurl)`

### PR DESCRIPTION
**Pull request by Fr0sT-Brutal**
Following https://github.com/pasdoc/pasdoc/pull/99

### CODE REVIEW

**Comment by Bi0T1N** [comment]
Wouldn't it be better to throw a warning for incorrect URLs instead of keep processing them?
The output is probably not what was intended 😄 
```
<p>(<a  href="http://example">http://example</a>)
<p>[Some descr] (<a  href="http://example">http://example</a>)
<p>[Some descr](<a  href="http://example">http://example</a></p>
```

**Comment by Fr0sT-Brutal** [comment]
> Wouldn't it be better to throw a warning for incorrect markdowns instead of keep processing them?
> The output is probably not what was intended

Actually, Markdown code stops processing them and exits but then another processing comes that searches for everything that looks like an URL and generates hrefs for them. We could disable that but I doubt it's a good decision. Auto-finding URLs is common and very widely used so one could expect the same from PasDoc.

**Comment by Bi0T1N** [comment]
> 
> 
> > Wouldn't it be better to throw a warning for incorrect markdowns instead of keep processing them?
> > The output is probably not what was intended
> 
> Actually, Markdown code stops processing them and exits but then another processing comes that searches for everything that looks like an URL and generates hrefs for them. We could disable that but I doubt it's a good decision. Auto-finding URLs is common and very widely used so one could expect the same from PasDoc.

Ah, true - I didn't thought about that. That shouldn't be changed.
> As for warnings... I'm unsure. While they're good for finding issues, in this case there could be many false positives which will produce annoying useless messages... Imagine PasDoc complaining on every `[` it found that is not a part of URL! I'm open for discussion of course

```
(http://example)
[Some descr] (http://example)
[Some descr](http://example
```
The first one shouldn't throw a warning as this could be intended for additional information.
But the second one is an obvious misuse of markdown by adding an extra whitespace and the last one could also throw a warning for missing closing bracket even if it could be complicated to handle that as there are URLs which contain `(` and `)` like https://en.wikipedia.org/wiki/Form_(HTML) - so it'd need to recognise that it has to end with `))`.

**Comment by Fr0sT-Brutal** [comment]
> ```
> (http://example)
> [Some descr] (http://example)
> [Some descr](http://example
> ```
> 
> The first one shouldn't throw a warning as this could be intended for additional information.
> But the second one is an obvious misuse of markdown by adding an extra whitespace and the last one could also throw a warning/hint for missing closing bracket even if it could be complicated to handle that as there are URLs which contain `(` and `)` like https://en.wikipedia.org/wiki/Form_(HTML) - so it'd need to recognise that it has to end with `))`.

Yeah, I missed the case of URLs containing brackets... They will produce incorrect results currently.
As for warnings: 2nd case could be non-trivial contrary to current dumb search for `](`. Code will have to search for `[`, then for `(` and then check if there's whitespace between them. 3rd case seems pretty easy to implement

TODO
[ ] Handle URLs with brackets
[ ] Produce warning on `[Some descr](http://example` case

**Comment by michaliskambi** [comment]
Merged, thank you (for doing it and updating testcase!).

As for warnings, I agree with your both conclusions:

- We detect and process URLs already (outside of Markdown processing), this should stay, so e.g. `(http://example)` shouldn't make a warning. I'm pretty sure I used it myself a few times :)

- `[Some descr] (http://example)` and `[Some descr](http://example` could produce a warning, as they are almost definitely a writer's mistake. But I get that detecting these cases, only to  make a warning, may be a major pain. So it can wait for next PR :)

**Comment by michaliskambi** [comment]
Hm I noticed something when looking at test output of

```
[Escaped \[\] descr](http://example)
```

The output (rendered by browser) shows a link `Escaped \[\] descr`. It should show `Escaped [] descr` instead. I mean the backslashes (used to escape) should *not* be visible in the output.

Quickly testing here on GitHub: [Escaped \[\] descr](http://example) . As you can see, the backslashes (that I internally used when writing it) are not visible in the output.

**Comment by michaliskambi** [comment]
I documented support for URLs in Markdown on https://github.com/pasdoc/pasdoc/wiki/MarkdownOption .

**Comment by Fr0sT-Brutal** [comment]
@michaliskambi that's reasonable, I'll fix it another PR

**Comment by Fr0sT-Brutal** [comment]
PR #104

**Pull request merged**
