### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Fr0sT-Brutal**

### CODE REVIEW

**Comment by michaliskambi** [comment]
I'm sorry for taking so long to review it! It looks cool, thank you for the improvements.

P.S. When adding / fixing something important, you're welcome to add it also to the ChangeLog file. This way we will announce this at next release to users.

**Comment by michaliskambi** [comment]
I pushed tiny fixes to compile and pass tests with FPC 3.0.4 on Linux, in https://github.com/pasdoc/pasdoc/commit/b5fb2c1e28c8600788536c0cf0dc80889b71ed90 and https://github.com/pasdoc/pasdoc/commit/c77ff8a37a6d51886025818c70d86cf1d10048f2 .

**Comment by Fr0sT-Brutal** [comment]
No problem, glad to see you back :)

> P.S. When adding / fixing something important, you're welcome to add it also to the ChangeLog file. This way we will announce this at next release to users.

Yeah, I keep forgetting about changelog, surely I'll try to remember adding something there :D

**Comment by Fr0sT-Brutal** [comment]
Additions to changelog, posting them here as they're too small to go through all this commit-PR-review-merge process
```
  * Scan implementation section of a unit in addition to default interface section
    https://github.com/pasdoc/pasdoc/wiki/ImplementationCommentsOption (Fr0sT-Brutal)
  * Parser improvements to correctly handle some special cases: reading chars > $FF,
    "*.inc" includes, files with Mac-style line endings (Fr0sT-Brutal)
  * Mem leaks fixed (Fr0sT-Brutal)
  * Tag parameters now could be multiline without enclosing parens by means of "line feed"
    character "\" (Fr0sT-Brutal)
```

**Comment by michaliskambi** [comment]
Thanks! I added the ChangeLog contents.

**Pull request merged**
