### PR TITLE
Markdown support

### PR DESCRIPTION
**Pull request by Fr0sT-Brutal**
Well, at last it reached more or less complete stage.
Wiki page is [here](https://github.com/Fr0sT-Brutal/pasdoc/wiki/MarkdownOption)

### CODE REVIEW

**Comment by michaliskambi** [comment]
Looks great, thank you! Merging.

**Comment by michaliskambi** [comment]
Thank you! Tested.

I pushed tiny improvements on top of your work:

- The ``` should have the same effect as `@preformatted` tag.
- To have Pascal code, one should use ```pascal

This is consistent with Markdown behaviour elsewhere as far as I see (and allows us to support syntax highlighting for other languages some day too :) ).

I created a wiki page https://github.com/pasdoc/pasdoc/wiki/MarkdownOption , using your text with small improvements.

**Comment by michaliskambi** [comment]
P.S. If you plan to extend it more, it may make sense to move parts of the code out from `PasDoc_TagManager.pas` to new unit like `PasDoc_Markdown.pas`. This would allow to keep `PasDoc_TagManager.pas` smaller  (dealing only with classes like TTag, TTagManager, and related classes).

**Comment by Fr0sT-Brutal** [comment]
> I pushed tiny improvements on top of your work:

Seem reasonable and nice :)

> P.S. If you plan to extend it more, it may make sense to move parts of the code out from `PasDoc_TagManager.pas` to new unit like `PasDoc_Markdown.pas`. This would allow to keep `PasDoc_TagManager.pas` smaller (dealing only with classes like TTag, TTagManager, and related classes).

Hmm, seems reasonable though that would require "exporting" `FindParagraph` and `FindChars` or extracting them to some common unit. I'll consider this in the future.

**Pull request merged**
