### PR TITLE
Brazilian Portuguese Translation and more...

### PR DESCRIPTION
**Pull request by carlosbfeitozafilho**
- Project group for all currently supported projects (Delphi Tokyo)
- Some "dcu" folders created to group generated dcu files
- Created the pasdoc_package_tokyo.dpk and related files to compile under Delphi Community Tokyo
- Brazilian translation updated
- Ignore list updated
- Translation problems:
  - Eventually some sentences have inverted order in portuguese, for example "Packed Record". In portuguese this is "Registro Comprimido", Packed = Comprimido and Record = Registro. The current way of translation do not have (I guess) a way to deal with this. In portuguese the full sentence translates to "Comprimido Registro" and this is wrong. It is something like "Record Packed" (equally wrong). To minimize this I'm enclosing the translation of "packed" between square brackets which generates "[Comprimido] Registro" something like "Record [Packed]". However, in english this sounds much better than portuguese :(

### CODE REVIEW

**Comment by michaliskambi** [comment]
Thank you! 

Everything looks cool, except I would like to avoid the `dcu` directories. We already have a subdirectory `lib` (only one, at the top-level of the repository) for a similar purpose with FPC/Lazarus, let's reuse it :) The `lib` is right now created by `make` execution (so you probably didn't know about it, if you didn't use the Makefile). 

So I would prefer to have Delphi output (like `*.dcu`) also go there, to the single `lib` subdirectory. And we can make it automatically existing (without the need to execute `make`). So:

- Please create `lib/.gitkeep` (only one, at the top-level of the repository). Remove other `.../dcu/.gitkeep` .

- Configure Delphi projects to place the DCU files in the top-level `lib/`.

Everything else is perfect, so once you do this I'll be happy to merge :)

I see the problem with "packed record". We should fix our translations to enable translating "packed record" as a whole, this way it could be properly translated. I added this to my TODO.

**Comment by carlosbfeitozafilho** [comment]
Hi @michaliskambi I've made the necessary modifications. Please let me know if there are some other problem

**Comment by michaliskambi** [comment]
Everything looks cool, thank you very much! Merged:)

**Comment by michaliskambi** [comment]
I have added your improvements to our ChangeLog file, on https://github.com/pasdoc/pasdoc/blob/master/ChangeLog . 

I hope I spelled your name correctly, if not please forgive me and let me know :)

**Comment by carlosbfeitozafilho** [comment]
Hi! I'm happy to help the project. The name is correcto, thank you!

I woud like to do interface improvements on pasdoc_gui. This is allowed? In
the Future, cuz now I'm out of time. If so, there are some limit on change
It?

Em sex, 2 de ago de 2019 17:36, Michalis Kamburelis <
notifications@github.com> escreveu:

**Comment by michaliskambi** [comment]
>  I woud like to do interface improvements on pasdoc_gui. This is allowed? In the Future, cuz now I'm out of time. If so, there are some limit on change It?

Of course, it's allowed and most welcome:) 

Please note that our official GUI (pasdoc_gui) is the one in `source/gui` subdirectory ( https://github.com/pasdoc/pasdoc/tree/master/source/gui ), and it is developed using FPC/Lazarus. The reasons are that :

- This way the GUI is cross-platform (also for Linux, macOS and other platforms. Debian is also packaging PasDoc so they'll probably compile it for lots of more platforms) .

- And this way it is developed using open-source tools (FPC, Lazarus), which are available to everyone forevever and on all OSes.

Be sure to use latest stable Lazarus to edit the forms. You can earlier announce what you plan to change, in case I have some comments, but in general I welcome all improvements :) 

The GUI available in `source/delphi_gui` ( https://github.com/pasdoc/pasdoc/tree/master/source/delphi_gui ) can be compiled with Delphi, but it is not released along with PasDoc (in our binary releases). It is mostly a test that our PasDoc components compile with Delphi (which we always want to guarantee -- PasDoc will always compile with both FPC/Lazarus and Delhi). It is available, but we don't actively develop it (it probably misses some functionality compared to source/gui/ ) and we don't release it in PasDoc binary releases.

Don't get me wrong, I don't want to come off as some "Delphi hater" :) Delphi is cool (esp. with new Community Edition available). And in general in PasDoc we want to always satisfy both Delphi and FPC/Lazarus developers :) But for the GUI we just had to make a choice: 1. either develop it with FPC/Lazarus, 2. or develop it with Delphi. We chose 1. I welcome contributions to both GUIs (source/gui and source/delphi_gui) in any case of course. 

In any case, there's no deadline, contributions are always welcome :) Thanks!

**Comment by carlosbfeitozafilho** [comment]
Hi!

I surely understand the Lazarus needed. 
I will install Lazarus to keep the things cross platform and as soon I have some time I will do some improvements.

Basically they will be interface improvements. PageControl using for easy the development and minor alignment adjusts. Maybe split the code between some forms (inside each tabsheet), well, each ting at its time ;) I'm planning only

**Pull request merged**
