### PR TITLE
Added param description and changed order param and para tags.

### PR DESCRIPTION
**Pull request by zekiguven**

### CODE REVIEW

**Comment by michaliskambi** [comment]
Thanks! Note that I'll be mostly offline during the week, but I'll apply it
on weekend:) It seems you also touch some unrelated code parts,
accidentally reverting some recent changes, can you check that? Thank you!

09.01.2017 5:14 AM "zekiguven" <notifications@github.com> napisał(a):

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/pasdoc/pasdoc/pull/5
Commit Summary

   - Added param description.

File Changes

   - *M* source/component/PasDoc_Parser.pas
   <https://github.com/pasdoc/pasdoc/pull/5/files#diff-0> (35)

Patch Links:

   - https://github.com/pasdoc/pasdoc/pull/5.patch
   - https://github.com/pasdoc/pasdoc/pull/5.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pasdoc/pasdoc/pull/5>, or mute the thread

**Comment by zekiguven** [comment]
Hi, 
> It seems you also touch some unrelated code parts,

Yes, İts seems. But not changed. 
Sample:
Diff shows: 
`-  Copyright 1998-2014 PasDoc developers.`
`+  Copyright 1998-2016 PasDoc developers.`

But already :
  Copyright 1998-2016 PasDoc developers.

Maybe git specific state, i dont know. 

Only changed below codes:
` s := ReplaceRegEx(s, '<param[ \t]+name[ \t]*=[ \t]*"([^"]*)"[ \t]*>*([^>]*)', '@param($1  $2');`
`  s := ReplaceRegEx(s, '</param>', ')'+LineEnding + LineEnding);`
`  s := ReplaceRegEx(s, '<para[^>]*>', LineEnding + LineEnding);`
`  s := ReplaceRegEx(s, '</para>', LineEnding + LineEnding);`

and tested.  its working.

**Comment by michaliskambi** [comment]
Ah, indeed. Thanks! Will apply on weekend!:)

09.01.2017 9:12 AM "zekiguven" <notifications@github.com> napisał(a):

Hi,

It seems you also touch some unrelated code parts,

Yes, İts seems. But not changed.
Sample:
Diff shows:
- Copyright 1998-2014 PasDoc developers.
+ Copyright 1998-2016 PasDoc developers.

But already :
Copyright 1998-2016 PasDoc developers.

Maybe git specific state, i dont know.

Only changed below codes:
s := ReplaceRegEx(s, '<param[ \t]+name[ \t]*=[ \t]*"([^"]*)"[
\t]*>*([^>]*)', '@param($1 $2');
s := ReplaceRegEx(s, '</param>', ')'+LineEnding + LineEnding);
s := ReplaceRegEx(s, '<para[^>]*>', LineEnding + LineEnding);
s := ReplaceRegEx(s, '</para>', LineEnding + LineEnding);

and tested. its working.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pasdoc/pasdoc/pull/5#issuecomment-271228816>, or mute
the thread

**Comment by michaliskambi** [comment]
I had a look, and applied your changes to <param>, thank you!

The support for <para> was already done in https://github.com/pasdoc/pasdoc/commit/aa192a6feef22b554270574fa4957a2b8a395cc9 . I resolved the conflict, keeping the existing support for <para>, it is equivalent to your changes (just done 2 lines earlier:).

**Pull request merged**
