### PR TITLE
Feature: parsing implementation section of a unit

### PR DESCRIPTION
**Pull request by Fr0sT-Brutal**
Finally, it reached somewhat usable state!

Must be merged after all commits from `dev` branch

### CODE REVIEW

**Comment by michaliskambi** [comment]
Thank you, I'll take care of merging soon.

One note: compilation with FPC 3.0.4 fails with 

```
PasDoc_Tokenizer.pas(770,18) Error: Identifier not found "Max"
PasDoc_Tokenizer.pas(770,9) Error: Incompatible types: got "untyped" expected "LongInt"
PasDoc_Tokenizer.pas(804,39) Warning: Implicit string type conversion with potential data loss from "WideChar" to "AnsiString"
PasDoc_Tokenizer.pas(1199) Fatal: There were 2 errors compiling module, stopping
```

Below is a full output from our Jenkins:

```
+ source /usr/local/fpclazarus/bin/setup.sh default
++ export FPCLAZARUS_VERSION=default
++ FPCLAZARUS_VERSION=default
++ echo 'Configured environment for FPC/Lazarus:' default
Configured environment for FPC/Lazarus: default
++ export PATH=/usr/local/fpclazarus/default/fpc/bin/:/usr/local/bin:/usr/bin:/bin:/usr/games
++ PATH=/usr/local/fpclazarus/default/fpc/bin/:/usr/local/bin:/usr/bin:/bin:/usr/games
+++ fpc -iV
++ export FPCLAZARUS_REAL_VERSION=3.0.4
++ FPCLAZARUS_REAL_VERSION=3.0.4
++ echo 'Real FPC version:' 3.0.4
Real FPC version: 3.0.4
++ export FPCDIR=/usr/local/fpclazarus/default/fpc/lib/fpc/3.0.4/
++ FPCDIR=/usr/local/fpclazarus/default/fpc/lib/fpc/3.0.4/
+ make
/bin/mkdir -p lib
/bin/mkdir -p bin
fpc -FEbin -FUlib @pasdoc-fpc.cfg -Fu./source/component -Fu./source/console -Fu./source/component/tipue -Fi./source/component -Fi./source/component/images ./source/console/pasdoc.dpr
Free Pascal Compiler version 3.0.4 [2017/10/03] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling ./source/console/pasdoc.dpr
Compiling ./source/console/PasDoc_Main.pas
Compiling ./source/component/PasDoc_Base.pas
Compiling ./source/component/PasDoc_Items.pas
Compiling ./source/component/PasDoc_Types.pas
Compiling ./source/component/PasDoc_StringVector.pas
Compiling ./source/component/PasDoc_Serialize.pas
Compiling ./source/component/PasDoc_StreamUtils.pas
Compiling ./source/component/PasDoc_Utils.pas
Compiling ./source/component/PasDoc_Versions.pas
Compiling ./source/component/PasDoc_ObjectVector.pas
Compiling ./source/component/PasDoc_Hashes.pas
Compiling ./source/component/PasDoc_TagManager.pas
PasDoc_TagManager.pas(774,3) Note: Local variable "SDummy" not used
Compiling ./source/component/PasDoc_SortSettings.pas
Compiling ./source/component/PasDoc_StringPairVector.pas
Compiling ./source/component/PasDoc_Tokenizer.pas
PasDoc_Tokenizer.pas(770,18) Error: Identifier not found "Max"
PasDoc_Tokenizer.pas(770,9) Error: Incompatible types: got "untyped" expected "LongInt"
PasDoc_Tokenizer.pas(804,39) Warning: Implicit string type conversion with potential data loss from "WideChar" to "AnsiString"
PasDoc_Tokenizer.pas(1199) Fatal: There were 2 errors compiling module, stopping
Fatal: Compilation aborted
Error: /usr/local/fpclazarus/3.0.4/fpc/bin/ppcx64 returned an error exitcode
```

**Comment by Fr0sT-Brutal** [comment]
I guess it could be solved by using Math unit

**Comment by michaliskambi** [comment]
Merged! Again, sorry for taking so long to review.

And many thanks for checking and extending our test suite in all your PRs -- I very appreciate it, this truly makes PasDoc reliable long-term. Thank you!

**Comment by Fr0sT-Brutal** [comment]
Better late than never :)
I guess now it's time for me to write some docs on this option `*sigh*`
Btw, check out how pretty the description could be with markdown and without the need to be short in interface section: [link](https://fr0st-brutal.github.io/Delphi_SChannelTLS/docs/SChannel.Utils.html#DoClientHandshake)

**Comment by Fr0sT-Brutal** [comment]
Wiki page: https://github.com/pasdoc/pasdoc/wiki/ImplementationCommentsOption

**Comment by michaliskambi** [comment]
Thank you for the documentation! I reworket it a bit, and I think it's cool now :)

I also moved the notes there about conditional compilation to the https://github.com/pasdoc/pasdoc/wiki/ConditionalDefines page, since they really apply to any parsing (of interface or implementation). I added there sections "Make sure the resulting code is valid" and "Support for $if" (it  supports a number of things :) ).

**Comment by Fr0sT-Brutal** [comment]
Yeah, now it's great :)

**Pull request merged**
