### PR TITLE
Improve conditional directive evaluation, define macros with -D

### PR DESCRIPTION
**Pull request by circular17**
This is a proposal to improve evaluation of `$IF` and `$ELSEIF` condition evaluation, so that there is no preprocessing needed before calling `pasdoc`.

To allow the use of predefined compiler macros, I've made so that using `:=` in the define option will actually set a macro. For example the option `-D FPC_FULLVERSION:=30202` will set the value of FreePascal compiler version, which can be used in compiler directives. This can be used in the `@` config file as well.

The expression evaluation retrieves the value of macros and parse their value. The operators are handled with precedence:

1. Function and subexpression
2. Negation: `not`
3. Multiplicative: `*` `/` `div` `mod` `and`
4. Additive: `+` `-` `or` (added `xor`)
5. Comparison: `=` `<=` `>=` `<` `>`

If there is a dangling token after the expression, it raises a warning but not an error, as it is accepted by FPC.

### CODE REVIEW

**Comment by circular17** [comment]
Here is a sample unit with directives:
```pascal
unit unit1;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils;

{ This should be true }
const _3Plus1Is4 =
{$IF 3 + 1 = 4}
true
{$ELSE}
false
{$ENDIF};

{ This should be true }
const _APlusBIsAB =
{$IF 'a' + 'b' = 'ab'}
true
{$ELSE}
false
{$ENDIF};

{ This should be true }
const _3Plus2Times2Is7 =
{$IF 3 + 2*2 = 7}
true
{$ELSE}
false
{$ENDIF};

{ This should be false }
const _3Minus1Is4 =
{$IF 3 - 1 = 4}
true
{$ELSE}
false
{$ENDIF};

{ This should be true }
const _3Minus2IsTrue =
{$IF 3 - 2}
true
{$ELSE}
false
{$ENDIF};


{ This should be true because NOT is 0 for all non zero integers }
const _Not3Is0 =
{$IF (NOT 3) = 0}
true
{$ELSE}
false
{$ENDIF};

const FPCVersionAtLeast322 =
{$IF FPC_FULLVERSION >= 30202}
true
{$ELSE}
false
{$ENDIF};

const FPCVersionAtLeast422 =
{$IF FPC_FULLVERSION >= 40202}
true
{$ELSE}
false
{$ENDIF};

implementation

end.
```

**Comment by circular17** [comment]
I need to look a bit further into the NOT operator because it seems it is not exactly doing what I thought.

**Review by michaliskambi — APPROVED** [review]

**Comment by michaliskambi** [comment]
Thank you!

I did small changes

- To code formatting
- Added your testcase from above comment https://github.com/pasdoc/pasdoc/pull/202#issuecomment-1968936148 to be automatically tested, so that it will never be broken accidentally
- Mentioned new stuff in [ChangeLog.md](https://github.com/pasdoc/pasdoc/blob/master/ChangeLog.md) and docs on https://pasdoc.github.io/ConditionalDefines

Note: I did find small issue, but frankly it may be easier to leave it unaddressed for now and avoid code complication in PasDoc: FPC `FPC_FULLVERSION` is a symbol only used for conditional compilation, it is *not* available as a regular macro when parsing Pascal source code. But our approach with `--define FPC_FULLVERSION:=30202` means we define FPC macro, which is also expanded by PasDoc during normal Pascal code parsing.

For example, this will *not* compile with FPC:

```delphi
MyConst = FPC_FULLVERSION;
```

But with PasDoc, with `--define FPC_FULLVERSION:=30202`, it will be processed and result in docs showing `MyConst = 30202;`. Here's a full testcase:

```delphi
unit ok_if_expressions_fpc_fullversion;

interface

const
  { This does not compile in FPC. }
  //MyConst = FPC_FULLVERSION;

  {$if FPC_FULLVERSION >= 30202}
  { Defined only when FPC >- 3.2.2. }
  MyConstIsFPC322 = 1;
  {$endif}

implementation

end.
```

However, I think we can just leave it. Introducing a separate set of symbols "only for conditional compilation" feels like an unnecessary overkill to deal with this.

**Comment by circular17** [comment]
Hi @michaliskambi 

Thank you very much for going into the details of the pull request. I agree wholeheartedly with your changes that show a fine understanding of my additions. They clarify some points and fix some typos.

Regarding the distinction between macros and predefined compiler variables, I came to the same conclusion as you. While in theory there is a difference, I don't think it is significant, at least for now at the current level of analysis of the units.

Warm regards

**Pull request merged**
